#include "wake_word.h"
#include "esp_log.h"
#include "esp_wn_iface.h"
// #include "hilexin.h"
// #include "hiesp.h"
#include "esp_wn_models.h"   // содержит esp_wn_handle_from_name

#include "esp_afe_sr_iface.h"
#include "esp_afe_sr_models.h"

#include "model_path.h"

static const char *TAG = "WAKE_WORD";
static const esp_wn_iface_t *wakenet = NULL;
static model_iface_data_t *model_data = NULL;


static int chunk_size = 0;

esp_err_t wake_word_init(const char *model_name) {

    srmodel_list_t *models = esp_srmodel_init("model");
    char *sys_model_name = esp_srmodel_filter(models, ESP_WN_PREFIX, model_name);

    // 1. Получаем интерфейс модели по имени
    wakenet = esp_wn_handle_from_name(sys_model_name);
    if (!wakenet) {
        ESP_LOGE(TAG, "Model '%s' not found!", sys_model_name);
        return ESP_FAIL;
    }

    // 2. Создаём экземпляр модели с порогом обнаружения
    model_data = wakenet->create(sys_model_name, DET_MODE_90);
    if (!model_data) {
        ESP_LOGE(TAG, "Failed to create model instance");
        return ESP_FAIL;
    }

    chunk_size = wakenet->get_samp_chunksize(model_data);
    ESP_LOGI(TAG, "Wake word initialized. Model: %s, chunk size: %d", sys_model_name, chunk_size);
    return ESP_OK;
}

bool wake_word_process(int16_t *samples, size_t sample_count) {
    if (!model_data || !wakenet) {
        return false;
    }
    if (sample_count != chunk_size) {
        ESP_LOGW(TAG, "Sample count mismatch: expected %d, got %d", chunk_size, sample_count);
        return false;
    }
    int state = wakenet->detect(model_data, samples);
    return (state == WAKENET_DETECTED);
}

int wake_word_get_chunk_size(void) {
    return chunk_size;
}


// AFE implementation
#include "esp_afe_sr_iface.h"
#include "esp_afe_sr_models.h"
//#include "esp_srmodel.h"

esp_afe_sr_iface_t *afe_handle = NULL;
esp_afe_sr_data_t *afe_data = NULL;
int afe_chunk_size = 0;
static int afe_channel_num = 1;

esp_err_t afe_init(const char *model_name) {
    // 1. Получаем список моделей из раздела "model"
    srmodel_list_t *models = esp_srmodel_init("model");
    if (!models) {
        ESP_LOGE("AFE", "No models found");
        return ESP_FAIL;
    }

        // 2. Выводим все доступные модели для отладки
    ESP_LOGI(TAG, "Available models (%d):", models->num);
    for (int i = 0; i < models->num; i++) {
        ESP_LOGI(TAG, "  [%d] %s", i, models->model_name[i]);
    }

    // 3. Фильтруем модель по префиксу "wn" и заданному имени
    char *wn_model = esp_srmodel_filter(models, "wn", model_name);
    if (!wn_model) {
        ESP_LOGE(TAG, "Model '%s' not found (with prefix 'wn')", model_name);
        return ESP_FAIL;
    }
    if (!wn_model) {
    ESP_LOGE(TAG, "wn_model is NULL!");
    return ESP_FAIL;
}
    ESP_LOGI(TAG, "Using wake net model: %s", wn_model);

    // 2. Создаём конфигурацию AFE для одного микрофона
    afe_config_t *afe_config = afe_config_init("M", models, AFE_TYPE_SR, AFE_MODE_HIGH_PERF);
    if (!afe_config) {
        ESP_LOGE("AFE", "Failed to init AFE config");
        return ESP_FAIL;
    }

    // 3. Включаем нужные компоненты
    afe_config->vad_init = false;
    afe_config->ns_init = false;

    afe_config->agc_init = true;
  //  afe_config->agc_config.gain = 15;           // Максимальное усиление (0-30)
    afe_config->agc_target_level_dbfs = -1; // Целевой уровень (ближе к 0 dB)
    afe_config->agc_compression_gain_db = 9; // Дополнительное сжатие
//    afe_agc_mode_t agc_mode; // The AGC mode for ASR. and the gain generated by AGC acts on the audio after far linear gain.
    

    afe_config->wakenet_init = true;
    afe_config->wakenet_model_name = wn_model;
    ESP_LOGI("AFE", "TEST1");
    // 4. Получаем интерфейс и создаём экземпляр
    afe_handle = esp_afe_handle_from_config(afe_config);

    if (afe_handle == NULL) {
    ESP_LOGE(TAG, "afe_handle is NULL after esp_afe_handle_from_config");
    return ESP_FAIL;
}
    
    ESP_LOGI("AFE", "afe_config->wakenet_model_name = %p (%s)", 
         afe_config->wakenet_model_name, afe_config->wakenet_model_name ? afe_config->wakenet_model_name : "NULL");
    // ESP_LOGI("AFE", "afe_config->models = %p, num = %d", 
    //      afe_config->models, afe_config->models ? afe_config->models->num : -1);
    
    afe_data = afe_handle->create_from_config(afe_config);
    ESP_LOGI("AFE", "TEST3");
    if (!afe_data) {
        ESP_LOGE("AFE", "Failed to create AFE data");
        return ESP_FAIL;
    }
    ESP_LOGI("AFE", "TEST4");
    afe_chunk_size = afe_handle->get_feed_chunksize(afe_data);
    afe_channel_num = afe_handle->get_feed_channel_num(afe_data);
    ESP_LOGI("AFE", "AFE initialized, chunk size: %d, channels: %d", afe_chunk_size, afe_channel_num);
    return ESP_OK;
}

bool afe_process(int16_t *samples, size_t sample_count, int16_t **processed, size_t *processed_samples) {
    if (!afe_handle || !afe_data) return false;
    if (sample_count != afe_chunk_size) {
        ESP_LOGW("AFE", "Wrong sample count: %d vs %d", sample_count, afe_chunk_size);
        return false;
    }

    // Передаём данные в AFE
    afe_handle->feed(afe_data, samples);

    // Забираем результат
    afe_fetch_result_t *res = afe_handle->fetch(afe_data);
    if (!res) {
        *processed = NULL;
        *processed_samples = 0;
        return false;
    }

    // Проверяем, есть ли обработанные данные
    if (res->data_size > 0) {
        *processed = res->data;
        *processed_samples = res->data_size / sizeof(int16_t);
    } else {
        *processed = NULL;
        *processed_samples = 0;
    }

    // Освобождаем результат (в некоторых версиях free, в других free_fetch)
    // Проверьте ваш заголовочный файл и используйте правильный метод
    //afe_handle->free_fetch(res); // возможно free_fetch(res)

    return true;
}

void afe_deinit(void) {
    if (afe_handle && afe_data) {
        afe_handle->destroy(afe_data);
        afe_data = NULL;
    }
}